// flow-typed signature: 6ffa154199ae7b908c37c58440f48456
// flow-typed version: <<STUB>>/eslint-plugin-angular_v^3.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-angular'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-angular' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-angular/environments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/gulpfile' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/angularelement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/avoid-scope-typos' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/component-limit' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/component-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/constant-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/controller-as-route' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/controller-as-vm' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/controller-as' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/controller-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/deferred' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/definedundefined' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/di-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/di-unused' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/di' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/directive-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/directive-restrict' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/document-service' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/dumb-inject' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/empty-controller' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/factory-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/file-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/filter-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/foreach' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/function-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/interval-service' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/json-functions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/log' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/module-dependency-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/module-getter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/module-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/module-setter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-angular-mock' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-controller' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-cookiestore' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-directive-replace' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-http-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-inline-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-jquery-angularelement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-private-call' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-run-logic' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-service-method' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/no-services' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/on-destroy' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/on-watch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/one-dependency-per-line' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/prefer-component' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/provider-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/rest-service' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/service-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/timeout-service' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/typecheck-array' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/typecheck-date' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/typecheck-function' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/typecheck-number' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/typecheck-object' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/typecheck-string' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/utils/angular-rule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/utils/false-values' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/utils/utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/value-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/watchers-execution' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/rules/window-service' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/scripts/docs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-angular/scripts/templates' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-angular/environments.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/environments'>;
}
declare module 'eslint-plugin-angular/gulpfile.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/gulpfile'>;
}
declare module 'eslint-plugin-angular/index' {
  declare module.exports: $Exports<'eslint-plugin-angular'>;
}
declare module 'eslint-plugin-angular/index.js' {
  declare module.exports: $Exports<'eslint-plugin-angular'>;
}
declare module 'eslint-plugin-angular/rules/angularelement.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/angularelement'>;
}
declare module 'eslint-plugin-angular/rules/avoid-scope-typos.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/avoid-scope-typos'>;
}
declare module 'eslint-plugin-angular/rules/component-limit.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/component-limit'>;
}
declare module 'eslint-plugin-angular/rules/component-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/component-name'>;
}
declare module 'eslint-plugin-angular/rules/constant-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/constant-name'>;
}
declare module 'eslint-plugin-angular/rules/controller-as-route.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/controller-as-route'>;
}
declare module 'eslint-plugin-angular/rules/controller-as-vm.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/controller-as-vm'>;
}
declare module 'eslint-plugin-angular/rules/controller-as.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/controller-as'>;
}
declare module 'eslint-plugin-angular/rules/controller-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/controller-name'>;
}
declare module 'eslint-plugin-angular/rules/deferred.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/deferred'>;
}
declare module 'eslint-plugin-angular/rules/definedundefined.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/definedundefined'>;
}
declare module 'eslint-plugin-angular/rules/di-order.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/di-order'>;
}
declare module 'eslint-plugin-angular/rules/di-unused.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/di-unused'>;
}
declare module 'eslint-plugin-angular/rules/di.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/di'>;
}
declare module 'eslint-plugin-angular/rules/directive-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/directive-name'>;
}
declare module 'eslint-plugin-angular/rules/directive-restrict.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/directive-restrict'>;
}
declare module 'eslint-plugin-angular/rules/document-service.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/document-service'>;
}
declare module 'eslint-plugin-angular/rules/dumb-inject.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/dumb-inject'>;
}
declare module 'eslint-plugin-angular/rules/empty-controller.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/empty-controller'>;
}
declare module 'eslint-plugin-angular/rules/factory-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/factory-name'>;
}
declare module 'eslint-plugin-angular/rules/file-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/file-name'>;
}
declare module 'eslint-plugin-angular/rules/filter-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/filter-name'>;
}
declare module 'eslint-plugin-angular/rules/foreach.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/foreach'>;
}
declare module 'eslint-plugin-angular/rules/function-type.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/function-type'>;
}
declare module 'eslint-plugin-angular/rules/interval-service.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/interval-service'>;
}
declare module 'eslint-plugin-angular/rules/json-functions.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/json-functions'>;
}
declare module 'eslint-plugin-angular/rules/log.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/log'>;
}
declare module 'eslint-plugin-angular/rules/module-dependency-order.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/module-dependency-order'>;
}
declare module 'eslint-plugin-angular/rules/module-getter.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/module-getter'>;
}
declare module 'eslint-plugin-angular/rules/module-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/module-name'>;
}
declare module 'eslint-plugin-angular/rules/module-setter.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/module-setter'>;
}
declare module 'eslint-plugin-angular/rules/no-angular-mock.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-angular-mock'>;
}
declare module 'eslint-plugin-angular/rules/no-controller.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-controller'>;
}
declare module 'eslint-plugin-angular/rules/no-cookiestore.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-cookiestore'>;
}
declare module 'eslint-plugin-angular/rules/no-directive-replace.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-directive-replace'>;
}
declare module 'eslint-plugin-angular/rules/no-http-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-http-callback'>;
}
declare module 'eslint-plugin-angular/rules/no-inline-template.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-inline-template'>;
}
declare module 'eslint-plugin-angular/rules/no-jquery-angularelement.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-jquery-angularelement'>;
}
declare module 'eslint-plugin-angular/rules/no-private-call.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-private-call'>;
}
declare module 'eslint-plugin-angular/rules/no-run-logic.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-run-logic'>;
}
declare module 'eslint-plugin-angular/rules/no-service-method.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-service-method'>;
}
declare module 'eslint-plugin-angular/rules/no-services.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/no-services'>;
}
declare module 'eslint-plugin-angular/rules/on-destroy.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/on-destroy'>;
}
declare module 'eslint-plugin-angular/rules/on-watch.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/on-watch'>;
}
declare module 'eslint-plugin-angular/rules/one-dependency-per-line.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/one-dependency-per-line'>;
}
declare module 'eslint-plugin-angular/rules/prefer-component.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/prefer-component'>;
}
declare module 'eslint-plugin-angular/rules/provider-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/provider-name'>;
}
declare module 'eslint-plugin-angular/rules/rest-service.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/rest-service'>;
}
declare module 'eslint-plugin-angular/rules/service-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/service-name'>;
}
declare module 'eslint-plugin-angular/rules/timeout-service.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/timeout-service'>;
}
declare module 'eslint-plugin-angular/rules/typecheck-array.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/typecheck-array'>;
}
declare module 'eslint-plugin-angular/rules/typecheck-date.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/typecheck-date'>;
}
declare module 'eslint-plugin-angular/rules/typecheck-function.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/typecheck-function'>;
}
declare module 'eslint-plugin-angular/rules/typecheck-number.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/typecheck-number'>;
}
declare module 'eslint-plugin-angular/rules/typecheck-object.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/typecheck-object'>;
}
declare module 'eslint-plugin-angular/rules/typecheck-string.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/typecheck-string'>;
}
declare module 'eslint-plugin-angular/rules/utils/angular-rule.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/utils/angular-rule'>;
}
declare module 'eslint-plugin-angular/rules/utils/false-values.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/utils/false-values'>;
}
declare module 'eslint-plugin-angular/rules/utils/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/utils/utils'>;
}
declare module 'eslint-plugin-angular/rules/value-name.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/value-name'>;
}
declare module 'eslint-plugin-angular/rules/watchers-execution.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/watchers-execution'>;
}
declare module 'eslint-plugin-angular/rules/window-service.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/rules/window-service'>;
}
declare module 'eslint-plugin-angular/scripts/docs.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/scripts/docs'>;
}
declare module 'eslint-plugin-angular/scripts/templates.js' {
  declare module.exports: $Exports<'eslint-plugin-angular/scripts/templates'>;
}
